version: "3"

services:
  nodeosd:
    image: eosio/eos-dev:latest
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 --replay-blockchain --hard-replay-blockchain
    #command: /opt/eosio/bin/nodeosd.sh --producer-name eosio --contracts-console --data-dir /opt/eosio/bin/data-dir -e --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 #--genesis-json /opt/eosio/bin/data-dir/genesis.json #--contracts-console #-e — Enable block production, even if the chain is stale
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
      - "9876"  
    volumes:
      - local-nodeos-data-volume:/opt/eosio/bin/data-dir
      - ./config-nodeosd1.ini:/opt/eosio/bin/data-dir/config.ini

  keosd:
    image: eosio/eos-dev:latest
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=localhost:8900 --http-alias=keosd:8900
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - local-keosd-data-volume:/opt/eosio/bin/data-dir
      - .:/config

  nodeosd-node2:
    image: eosio/eos-dev:latest
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir --replay-blockchain --hard-replay-blockchain
    hostname: nodeosd-node2
    ports:
      - 8889:8889
      - 9877:9877
    expose:
      - "8889"
    links:
      - nodeosd
    container_name: nodeosd-node2
    volumes:
      - local-nodeos-data-node2-volume:/opt/eosio/bin/data-dir
      - ./config-nodeosd2.ini:/opt/eosio/bin/data-dir/config.ini
 
  keosd-node2:
    image: eosio/eos-dev:latest
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=localhost:8900 --http-alias=keosd:8900
    hostname: keosd-node2
    links:
      - nodeosd-node2
    container_name: keosd-node2
    volumes:
      - local-keosd-data-node2-volume:/opt/eosio/bin/data-dir
      - .:/config

volumes:
 local-nodeos-data-volume:
   external: true
 local-keosd-data-volume:
   external: true
 local-nodeos-data-node2-volume:
   external: true
 local-keosd-data-node2-volume:
   external: true
